{% set version = "0.5.6" %}

package:
  name: msgpack-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack/msgpack-{{ version }}.tar.gz
  sha256: 0ee8c8c85aa651be3aa0cd005b5931769eaa658c948ce79428766f1bd46ae2c3

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.16
  run:
    - python

test:
  imports:
    - msgpack

about:
  home: http://msgpack.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'MessagePack (de)serializer'
  license_family: Apache
  dev_url: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - ocefpaf
