travis:
  secure:
    BINSTAR_TOKEN: j5O2+3yQUEFxeZCnz6J2sb2qCvOveZO8JfgJv5OsRRtkcWV5wQqt9ionBJwsSxhWX7bsWRa0uXZePoORvK0DL524w/sJEwVhi/W4+nnSgxltsLgVf3gbunReU0MbhT83sx6XO/hVsS0MwXF4m0mFHe7U4RRYRtzbp/R98gB9dyXywKqo5HOsyy7Wty38EtetyV64sqsWCnuJe9FCOa7Ce0jFy+BgdKj1XnI95VugS2GBOqhvnVdHRo+sTp97SOitEfrkJ8f/HkrVbNpl1vATwe9zmyDywY2WCiOc4lzMlgL3kz6n3FTuwA1eTJBSlr1Q66uzJloHn+44VaoAv0Xm7ph52Vhz6uGen10JBStyTF7ak0LAmzr0hgT/8GHvX4SyNjd2HCwQE/uKnpAjoW/P05ZnJQLy7P5hf4DwwcdCrVDxbYqiG2+HKXpDPEmbsJG2ic+1WzxxpUJGr7Sl8Wq9k/okj/LDK6HHD7IF12oUQjTqcuCAtBdQYDWFswD6iaVKFgZrPquX+f/wHsfgIwPNN+UPv8CkY0CvuW8rQSCg8keRNnpUK3KnyN7lWy/qbWn2Afs0rKnjBHweIuFx4dJ9lL71MygbHmFqLCOCh7qoWQHPCGGi5zlsyN8ksCgxqPhJZryl2+oSbIUeybWhP1MGgIXAW8KUy/oHorbrgTRnjWE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
